from __future__ import annotations

from enum import Enum


class AnalysisTrigger(str, Enum):
    MANUAL = "MANUAL"
    API = "API"
    SCHEDULED = "SCHEDULED"


class AnalysisRunStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class CandidateStatus(str, Enum):
    PENDING_EVALUATION = "PENDING_EVALUATION"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    BELOW_THRESHOLD = "BELOW_THRESHOLD"
    NOT_EXECUTABLE = "NOT_EXECUTABLE"


class PreparationStatus(str, Enum):
    PREPARED = "PREPARED"
    RESERVED = "RESERVED"
    CONFIRMED = "CONFIRMED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class PaperOrderStatus(str, Enum):
    SUBMITTED = "SUBMITTED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class AssetType(str, Enum):
    EQUITY = "EQUITY"
    ETF = "ETF"
    CRYPTO = "CRYPTO"
    FX = "FX"
    CURRENCY = "CURRENCY"
    CASH = "CASH"
    BANK_BALANCE = "BANK_BALANCE"
    UNKNOWN = "UNKNOWN"


ELIGIBLE_HARVEST_ASSET_TYPES = frozenset({AssetType.EQUITY, AssetType.ETF, AssetType.CRYPTO})
INELIGIBLE_HARVEST_ASSET_TYPES = frozenset(
    {
        AssetType.FX,
        AssetType.CURRENCY,
        AssetType.CASH,
        AssetType.BANK_BALANCE,
        AssetType.UNKNOWN,
    }
)


class DebitCredit(str, Enum):
    DEBIT = "DEBIT"
    CREDIT = "CREDIT"


class HoldingPeriod(str, Enum):
    SHORT_TERM = "SHORT_TERM"
    LONG_TERM = "LONG_TERM"


class MLStatus(str, Enum):
    FITTED = "FITTED"
    INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"


class ConflictLabel(str, Enum):
    NEW = "NEW"
    STILL_ACTIVE = "STILL_ACTIVE"
    RESOLVED = "RESOLVED"
    SUPERSEDED = "SUPERSEDED"


class ConflictActiveStatus(str, Enum):
    ACTIVE = "ACTIVE"
    RESOLVED = "RESOLVED"
    SUPERSEDED = "SUPERSEDED"


class StatementFormat(str, Enum):
    SYNTHETIC_BANK_V1 = "SYNTHETIC_BANK_V1"
    SYNTHETIC_BROKERAGE_V1 = "SYNTHETIC_BROKERAGE_V1"


class AccountType(str, Enum):
    BANK = "BANK"
    BROKERAGE = "BROKERAGE"


class ReplacementKind(str, Enum):
    ALLOWED = "ALLOWED"
    SUBSTANTIALLY_IDENTICAL = "SUBSTANTIALLY_IDENTICAL"
    PROHIBITED = "PROHIBITED"
    UNKNOWN = "UNKNOWN"


class RejectionCode(str, Enum):
    NOT_TAXABLE_ACCOUNT = "NOT_TAXABLE_ACCOUNT"
    INELIGIBLE_ASSET_TYPE = "INELIGIBLE_ASSET_TYPE"
    MISSING_BASIS = "MISSING_BASIS"
    INVALID_BASIS = "INVALID_BASIS"
    NON_POSITIVE_QUANTITY = "NON_POSITIVE_QUANTITY"
    STALE_QUOTE = "STALE_QUOTE"
    UNAVAILABLE_QUOTE = "UNAVAILABLE_QUOTE"
    BELOW_THRESHOLD = "BELOW_THRESHOLD"
    WASH_SALE_CONFLICT = "WASH_SALE_CONFLICT"
    CRYPTO_REPURCHASE_CONFLICT = "CRYPTO_REPURCHASE_CONFLICT"
    RISK_PROFILE_VIOLATION = "RISK_PROFILE_VIOLATION"
    MAX_TRADE_SIZE = "MAX_TRADE_SIZE"
    REPLACEMENT_NOT_ALLOWED = "REPLACEMENT_NOT_ALLOWED"
    SUBSTANTIALLY_IDENTICAL_REPLACEMENT = "SUBSTANTIALLY_IDENTICAL_REPLACEMENT"
    UNKNOWN_REPLACEMENT = "UNKNOWN_REPLACEMENT"
    NOT_TRADABLE = "NOT_TRADABLE"
    INSUFFICIENT_MIRROR_QUANTITY = "INSUFFICIENT_MIRROR_QUANTITY"
    DATA_STALE = "DATA_STALE"
    INCOMPLETE_HISTORY = "INCOMPLETE_HISTORY"
    POSITION_MISMATCH = "POSITION_MISMATCH"
    PREVIOUSLY_EXECUTED = "PREVIOUSLY_EXECUTED"
    PROFITABLE_LOT = "PROFITABLE_LOT"
    NO_UNREALIZED_LOSS = "NO_UNREALIZED_LOSS"


class TransactionType(str, Enum):
    PURCHASE = "PURCHASE"
    SALE = "SALE"
    DIVIDEND = "DIVIDEND"
    REINVESTMENT = "REINVESTMENT"
    TRANSFER = "TRANSFER"
    WITHDRAWAL = "WITHDRAWAL"
    REFUND = "REFUND"
    INTEREST = "INTEREST"
    FEE = "FEE"
    PAYMENT = "PAYMENT"
    DEPOSIT = "DEPOSIT"
    OTHER = "OTHER"


class ParseErrorCode(str, Enum):
    UNKNOWN_FORMAT = "UNKNOWN_FORMAT"
    MALFORMED_STATEMENT = "MALFORMED_STATEMENT"
    INSUFFICIENT_TEXT = "INSUFFICIENT_TEXT"
    RECONCILIATION_FAILED = "RECONCILIATION_FAILED"
    INVALID_DATE = "INVALID_DATE"
    INVALID_CURRENCY = "INVALID_CURRENCY"
    INVALID_NUMERIC = "INVALID_NUMERIC"
    PAGE_CONTINUITY = "PAGE_CONTINUITY"
    MISSING_HEADER = "MISSING_HEADER"
    COLUMN_MISMATCH = "COLUMN_MISMATCH"
    ROW_FIELD_COUNT = "ROW_FIELD_COUNT"


class WindowLogicalPrefix(str, Enum):
    QUOTE = "QUOTE"
    PRICE_WINDOW = "PRICE_WINDOW"
    ANOMALY_WINDOW = "ANOMALY_WINDOW"
    FX = "FX"
    WINDOW_META = "WINDOW_META"


PERSISTABLE_CONFLICT_CODES = frozenset(
    {
        RejectionCode.WASH_SALE_CONFLICT,
        RejectionCode.CRYPTO_REPURCHASE_CONFLICT,
        RejectionCode.RISK_PROFILE_VIOLATION,
        RejectionCode.REPLACEMENT_NOT_ALLOWED,
        RejectionCode.SUBSTANTIALLY_IDENTICAL_REPLACEMENT,
        RejectionCode.UNKNOWN_REPLACEMENT,
        RejectionCode.STALE_QUOTE,
        RejectionCode.UNAVAILABLE_QUOTE,
        RejectionCode.INSUFFICIENT_MIRROR_QUANTITY,
        RejectionCode.DATA_STALE,
        RejectionCode.INCOMPLETE_HISTORY,
        RejectionCode.POSITION_MISMATCH,
        RejectionCode.NOT_TRADABLE,
    }
)
