"""phase1 initial schema

Revision ID: e74aa3e4d0fa
Revises: 
Create Date: 2026-08-28 01:46:26.489904
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = 'e74aa3e4d0fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_id', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_id', name='uq_assets_canonical_id')
    )
    op.create_table('replacement_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_canonical_id', sa.String(length=128), nullable=False),
    sa.Column('replacement_canonical_id', sa.String(length=128), nullable=False),
    sa.Column('relationship', sa.String(length=32), nullable=False),
    sa.Column('rule_version', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_canonical_id', 'replacement_canonical_id', 'rule_version', name='uq_replacement_rel')
    )
    op.create_table('rolling_window_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('logical_key', sa.String(length=255), nullable=False),
    sa.Column('sort_key', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logical_key', 'sort_key', name='uq_rolling_window_identity')
    )
    op.create_index('ix_rolling_window_logical', 'rolling_window_records', ['logical_key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('agent_conversation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_conversation_sessions_user_id'), 'agent_conversation_sessions', ['user_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('as_of_period', sa.Date(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('ml_status', sa.String(length=32), nullable=True),
    sa.Column('rule_version', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_analysis_runs_idempotency')
    )
    op.create_index('ix_analysis_runs_user_asof', 'analysis_runs', ['user_id', 'as_of_period'], unique=False)
    op.create_table('portfolio_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('alpaca_alias', sa.String(length=64), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_accounts_user_id'), 'portfolio_accounts', ['user_id'], unique=False)
    op.create_table('provider_asset_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('provider_symbol', sa.String(length=64), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name', 'provider_symbol', name='uq_provider_asset_mapping')
    )
    op.create_index(op.f('ix_provider_asset_mappings_asset_id'), 'provider_asset_mappings', ['asset_id'], unique=False)
    op.create_table('agent_conversation_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_conversation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_conversation_items_session_id'), 'agent_conversation_items', ['session_id'], unique=False)
    op.create_table('brokerage_dividends',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_transaction_id', sa.String(length=128), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('reinvested', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_transaction_id', name='uq_dividends_external_id')
    )
    op.create_index(op.f('ix_brokerage_dividends_portfolio_id'), 'brokerage_dividends', ['portfolio_id'], unique=False)
    op.create_table('brokerage_purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_transaction_id', sa.String(length=128), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('is_reinvestment', sa.Boolean(), nullable=False),
    sa.Column('is_scheduled_crypto', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_transaction_id', name='uq_purchases_external_id')
    )
    op.create_index(op.f('ix_brokerage_purchases_portfolio_id'), 'brokerage_purchases', ['portfolio_id'], unique=False)
    op.create_table('brokerage_sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_transaction_id', sa.String(length=128), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('acquisition_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sale_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('proceeds', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('allocated_basis', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('realized_result', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('holding_period', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['portfolio_accounts.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_transaction_id', name='uq_sales_external_id')
    )
    op.create_index(op.f('ix_brokerage_sales_portfolio_id'), 'brokerage_sales', ['portfolio_id'], unique=False)
    op.create_table('mirror_manifests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('alpaca_alias', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', name='uq_mirror_portfolio')
    )
    op.create_table('paper_mirror_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('alpaca_alias', sa.String(length=64), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_mirror_activity_portfolio_id'), 'paper_mirror_activity', ['portfolio_id'], unique=False)
    op.create_table('portfolio_analysis_locks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('as_of_period', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_active_portfolio_period', 'portfolio_analysis_locks', ['portfolio_id', 'as_of_period'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('risk_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('max_crypto_weight', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('max_single_asset_weight', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('max_equity_weight', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('min_bond_weight', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('max_volatility', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('max_trade_notional', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('max_turnover', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('rule_version', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id')
    )
    op.create_table('statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_statement_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=True),
    sa.Column('format', sa.String(length=64), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('closing_balance', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('parsing_confidence', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['portfolio_accounts.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_statement_id', name='uq_statements_external_id')
    )
    op.create_index(op.f('ix_statements_account_id'), 'statements', ['account_id'], unique=False)
    op.create_index(op.f('ix_statements_user_id'), 'statements', ['user_id'], unique=False)
    op.create_table('target_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('asset_class', sa.String(length=32), nullable=False),
    sa.Column('canonical_asset_id', sa.String(length=128), nullable=True),
    sa.Column('target_weight', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('rule_version', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'asset_class', 'canonical_asset_id', name='uq_target_alloc')
    )
    op.create_index(op.f('ix_target_allocations_portfolio_id'), 'target_allocations', ['portfolio_id'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('statement_id', sa.UUID(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_accounts.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_holdings_portfolio_asset', 'holdings', ['portfolio_id', 'asset_id'], unique=False)
    op.create_table('tax_lots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_lot_id', sa.String(length=128), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('source_statement_id', sa.UUID(), nullable=True),
    sa.Column('acquisition_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('original_quantity', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('per_unit_basis', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('remaining_basis', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('statement_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('missing_basis', sa.Boolean(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('remaining_quantity >= 0', name='ck_tax_lots_remaining_qty'),
    sa.ForeignKeyConstraint(['account_id'], ['portfolio_accounts.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_accounts.id'], ),
    sa.ForeignKeyConstraint(['source_statement_id'], ['statements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_lot_id', name='uq_tax_lots_external_id')
    )
    op.create_index('ix_tax_lots_portfolio_asset', 'tax_lots', ['portfolio_id', 'asset_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_transaction_id', sa.String(length=128), nullable=False),
    sa.Column('statement_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('txn_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('normalized_merchant', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('txn_type', sa.String(length=32), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('original_currency', sa.String(length=8), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('converted_amount', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('running_balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=20, scale=12), nullable=True),
    sa.Column('fx_requested_date', sa.Date(), nullable=True),
    sa.Column('fx_effective_date', sa.Date(), nullable=True),
    sa.Column('fx_provider', sa.String(length=64), nullable=True),
    sa.Column('parsing_confidence', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['portfolio_accounts.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_transaction_id', name='uq_transactions_external_id')
    )
    op.create_index('ix_transactions_account_date', 'transactions', ['account_id', 'txn_date'], unique=False)
    op.create_index('ix_transactions_category', 'transactions', ['category'], unique=False)
    op.create_index('ix_transactions_merchant', 'transactions', ['normalized_merchant'], unique=False)
    op.create_index(op.f('ix_transactions_statement_id'), 'transactions', ['statement_id'], unique=False)
    op.create_index('ix_transactions_user_date', 'transactions', ['user_id', 'txn_date'], unique=False)
    op.create_table('anomaly_ground_truth',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=64), nullable=False),
    sa.Column('injected_reason', sa.Text(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_anomaly_ground_truth_user_id'), 'anomaly_ground_truth', ['user_id'], unique=False)
    op.create_table('anomaly_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('raw_decision_score', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.Column('normalized_score', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('feature_set_version', sa.String(length=64), nullable=False),
    sa.Column('ml_status', sa.String(length=32), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'transaction_id', name='uq_anomaly_score_run_txn')
    )
    op.create_table('harvesting_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('tax_lot_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_accounts.id'], ),
    sa.ForeignKeyConstraint(['tax_lot_id'], ['tax_lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'tax_lot_id', name='uq_candidate_run_lot')
    )
    op.create_index('ix_candidates_status', 'harvesting_candidates', ['status'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rejection_code', sa.String(length=64), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('rule_version', sa.String(length=64), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('conflict_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('conflict_label', sa.String(length=16), nullable=True),
    sa.Column('usable_loss', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('total_loss', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('selected_quantity', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('quote', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('quote_provider', sa.String(length=64), nullable=True),
    sa.Column('basis', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('target_before', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('target_after', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('risk_effect', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('drift_effect', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('replacement_canonical_id', sa.String(length=128), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('tie_breaker_explanation', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['harvesting_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_candidate_id'), 'evaluations', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_evaluations_conflict_fingerprint'), 'evaluations', ['conflict_fingerprint'], unique=False)
    op.create_table('execution_preparations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['harvesting_candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.create_table('candidate_conflict_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('tax_lot_id', sa.UUID(), nullable=False),
    sa.Column('canonical_asset_id', sa.String(length=128), nullable=False),
    sa.Column('rejection_code', sa.String(length=64), nullable=False),
    sa.Column('rule_version', sa.String(length=64), nullable=False),
    sa.Column('replacement_canonical_id', sa.String(length=128), nullable=True),
    sa.Column('conflict_window_start', sa.Date(), nullable=True),
    sa.Column('conflict_window_end', sa.Date(), nullable=True),
    sa.Column('conflicting_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('active_status', sa.String(length=16), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('latest_candidate_id', sa.UUID(), nullable=True),
    sa.Column('latest_evaluation_id', sa.UUID(), nullable=True),
    sa.Column('canonical_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['latest_candidate_id'], ['harvesting_candidates.id'], ),
    sa.ForeignKeyConstraint(['latest_evaluation_id'], ['evaluations.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_accounts.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['candidate_conflict_identities.id'], ),
    sa.ForeignKeyConstraint(['tax_lot_id'], ['tax_lots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint', name='uq_conflict_fingerprint')
    )
    op.create_table('paper_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('preparation_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider_order_id', sa.String(length=128), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_quantity', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['preparation_id'], ['execution_preparations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_orders_preparation_id'), 'paper_orders', ['preparation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_orders_preparation_id'), table_name='paper_orders')
    op.drop_table('paper_orders')
    op.drop_table('candidate_conflict_identities')
    op.drop_table('execution_preparations')
    op.drop_index(op.f('ix_evaluations_conflict_fingerprint'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_candidate_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index('ix_candidates_status', table_name='harvesting_candidates')
    op.drop_table('harvesting_candidates')
    op.drop_table('anomaly_scores')
    op.drop_index(op.f('ix_anomaly_ground_truth_user_id'), table_name='anomaly_ground_truth')
    op.drop_table('anomaly_ground_truth')
    op.drop_index('ix_transactions_user_date', table_name='transactions')
    op.drop_index(op.f('ix_transactions_statement_id'), table_name='transactions')
    op.drop_index('ix_transactions_merchant', table_name='transactions')
    op.drop_index('ix_transactions_category', table_name='transactions')
    op.drop_index('ix_transactions_account_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_tax_lots_portfolio_asset', table_name='tax_lots')
    op.drop_table('tax_lots')
    op.drop_index('ix_holdings_portfolio_asset', table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_target_allocations_portfolio_id'), table_name='target_allocations')
    op.drop_table('target_allocations')
    op.drop_index(op.f('ix_statements_user_id'), table_name='statements')
    op.drop_index(op.f('ix_statements_account_id'), table_name='statements')
    op.drop_table('statements')
    op.drop_table('risk_profiles')
    op.drop_index('uq_active_portfolio_period', table_name='portfolio_analysis_locks', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_table('portfolio_analysis_locks')
    op.drop_index(op.f('ix_paper_mirror_activity_portfolio_id'), table_name='paper_mirror_activity')
    op.drop_table('paper_mirror_activity')
    op.drop_table('mirror_manifests')
    op.drop_index(op.f('ix_brokerage_sales_portfolio_id'), table_name='brokerage_sales')
    op.drop_table('brokerage_sales')
    op.drop_index(op.f('ix_brokerage_purchases_portfolio_id'), table_name='brokerage_purchases')
    op.drop_table('brokerage_purchases')
    op.drop_index(op.f('ix_brokerage_dividends_portfolio_id'), table_name='brokerage_dividends')
    op.drop_table('brokerage_dividends')
    op.drop_index(op.f('ix_agent_conversation_items_session_id'), table_name='agent_conversation_items')
    op.drop_table('agent_conversation_items')
    op.drop_index(op.f('ix_provider_asset_mappings_asset_id'), table_name='provider_asset_mappings')
    op.drop_table('provider_asset_mappings')
    op.drop_index(op.f('ix_portfolio_accounts_user_id'), table_name='portfolio_accounts')
    op.drop_table('portfolio_accounts')
    op.drop_index('ix_analysis_runs_user_asof', table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_agent_conversation_sessions_user_id'), table_name='agent_conversation_sessions')
    op.drop_table('agent_conversation_sessions')
    op.drop_table('users')
    op.drop_index('ix_rolling_window_logical', table_name='rolling_window_records')
    op.drop_table('rolling_window_records')
    op.drop_table('replacement_relationships')
    op.drop_table('assets')
    # ### end Alembic commands ###
